#!/usr/bin/env bash

#trap "pkill -f ${0##*/}" INT

#trap "kill $(jobs -p)"  HUP INT QUIT TERM PWR EXIT
#pid=$$

key_server='hkps://keyserver.ubuntu.com'
# keyservers
#hkps://pgp.surf.nl (ex-SKS pool)
#hkp://pgp.rediris.es
echo $$ >/tmp/llaves.pid

SHELL=/bin/bash
#trap "kill $$" HUP INT PWR EXIT
trap '' TSTP
trap "kill -9 $(cat /tmp/llaves.pid)" HUP INT PWR EXIT

_colorize() {
  local string
  string="${1//\[/\\033\[0;32m\[}"
  string="${string//\]/\]\\033\[0m}"
  printf '%b\n' "${string}"
}

export -f _colorize

edit_key=ctrl-e
revok_key=ctrl-a
recv_keys=ctrl-r
tab=tab
key_gen=ctrl-g
del_key=ctrl-d
exp_key=ctrl-x
imp_key=ctrl-k
upload_key=ctrl-u
#search_key=ctrl-k

export HEADER="$(_colorize "[$key_gen] Generar llaves [$del_key] Eliminar clave
[$exp_key] Exportar llave [$tab] cambio entre llaveros [$revok_key] Revocar clave
[$edit_key] Editar llave [$recv_keys] Recibir llaves
[$imp_key] Importar llave [$upload_key] Subir llave [ctrl-f] manejar archivos
")

"

_desencriptar() {
  gpg --decrypt "$1"
}

_listar_archivos() {
  export HEADER="$(_colorize "[ctrl-n] Desencriptar [$del_key] Eliminar clave
  [$exp_key] Exportar llave [$tab] cambio entre llaveros [$revok_key] Revocar clave
  ")"
  find . -maxdepth 1 -name '.git*' -prune -o -printf '%P\n' -type f |
    fzf \
    --cycle \
    --bind "ctrl-n:execute(_desencriptar {})" \
    --bind "ctrl-p:execute(_encriptar {})" \
    --bind "ctrl-m:execute(_encriptar {})" \
    --header="$HEADER"
}

_importar_llave() {
  _listar_archivos | fzf | xargs -r gpg --import
}

_eliminar_clave() {
  gpg --delete-secret-keys $1 2>/dev/null
  gpg --delete-keys "$1" 2>/dev/null
  ! gpg --list-keys "$1" 2>/dev/null &&
    notify-send "clave eliminada con exito"
}

_encriptar_simetricamente() {
  gpg --symmetric "$@"
}

_verificar_firma_digital() {
  gpg --verify $1 $2
}

_firmar_digitalmente() {
  _claves_publicas | fzf --prompt='claves publicas'
  gpg --detach-sign $1 $2
}

_exportar_clave() {
  gpg --export "$@"
}

_encriptar_asimetricamente() {
  gpg --encrypt "$@"
}

_crear_par_de_llaves() {
  gpg --full-generate-key --expert
}

_claves_privadas() {
  gpg --keyid-format LONG -K --with-colons |
    grep '^uid' | cut -d':' -f2,10 | tr ':' ' '
}

_claves_publicas() {
  gpg --list-keys --with-colons | sed -n -e '/^pub/,/^uid/p' |
    grep '^uid' | cut -d':' -f2,10 | tr ':' ' '
}

_revocar_clave() {
  printf '%s' "quieres dejar sin validez $1 (s/n) "
  read -r respuesta
  [ "$respuesta" = 's' ] || return
  huella=$(gpg --list-keys --with-colons $1 |
    grep -m1 '^fpr' | cut -d':' -f10)
  gpg --output revoke.asc --gen-revoke $huella || return
  gpg --import revoke.asc
  gpg --keyserver $key_server \
    --search-keys $huella
  gpg --keyserver $key_server --send-keys $huella
}

_copiar_portapapeles() {
  echo \"$1\" | xargs gpg --list-key --with-colons {} |
    grep -m1 '^fpr' | cut -d':' -f10 | xclip -r -sel clipboard &&
    notify-send "copiado huella de llave al portapapeles" 2>/dev/null
}

_search_key() {
  uid=$(xclip -o | cut -d'/' -f2)
  gpg --keyserver $key_server --search-keys $uid
  #  gpg --list-key $uid \
  #    && notify-send "llave importada correctamente"
}

_subir_clave() {
  printf '%s' "quieres compartir la llave $1? (s/n) "
  read -r respuesta
  [ "$respuesta" = 's' ] || return
  llave=$(gpg --with-colons --list-key $1 |
    grep -m 1 '^fpr' | cut -d':' -f10)
  [ "$llave" ] && gpg --keyserver $key_server --send-keys $llave
}

main() {
  #HEADER="$(_colorize "[${key_gen}] Generar llaves [Escape] Exit
  #[${tab^^}] moverse entre llaveros [${install_pkgs^^}] Install package
  #[${set_fastest_mirrors^^}] set fastest mirrors [${list_installed^^}] list Installed
  #")
  #"

  _claves_privadas | fzf --preview="gpg --list-key {2..}" \
    --header="$HEADER" \
    --prompt='LLAVERO PRIVADO: ' \
    --inline-info \
    --bind "ctrl-x:execute(gpg --output {2..}.pgp --armor --export-secret-key {2..} )" \
    --bind "ctrl-f:execute(_firmar_digitalmente)" \
    --bind "ctrl-e:execute(gpg --edit-key {2..})" \
    --bind "ctrl-d:execute(_eliminar_clave)+reload(_claves_privadas)" \
    --bind "ctrl-a:execute(_revocar_clave {2..})+reload(_claves_privadas)" \
    --bind "ctrl-r:execute(_search_key)+reload(_claves_privadas)" \
    --bind "ctrl-k:execute(_importar_llave)+reload(_claves_privadas)" \
    --bind "ctrl-u:execute(_subir_clave {2..})" \
    --bind "ctrl-g:execute(_crear_par_de_llaves)+reload(_claves_privadas)" \
    --bind "ctrl-m:execute(gpg --with-colons --list-key {2..})" \
    --bind "enter:execute:_copiar_portapapeles {2..}" \
    --bind "tab:abort" \
    --preview-window="down:wrap:10"
}

sec() {
  _claves_publicas | fzf --preview="gpg --list-key {2..}" \
    --header="$HEADER" \
    --prompt='LLAVERO PUBLICO: ' \
    --inline-info \
    --bind change:first \
    --bind "ctrl-d:execute(_eliminar_clave {2..})+reload(_claves_publicas)" \
    --bind "ctrl-a:execute(_revocar_clave {2..})+reload(_claves_publicas)" \
    --bind "ctrl-x:execute(gpg --output {2..}.pgp --armor --export {2..} )" \
    --bind "ctrl-u:execute(_subir_clave {2..})" \
    --bind "ctrl-r:execute(_search_key)+reload(_claves_publicas)" \
    --bind "ctrl-e:execute(gpg --edit-key {2..})" \
    --bind "ctrl-g:execute(_crear_par_de_llaves)+reload(_claves_publicas)" \
    --bind "enter:execute:_copiar_portapapeles {2..}" \
    --bind "ctrl-f:execute:_listar_archivos" \
    --bind "ctrl-k:execute(_importar_llave )+reload(_claves_publicas)" \
    --bind "tab:execute(main)" \
    --preview-window="down:wrap:10"
}

export -f main sec _verificar_firma_digital _claves_privadas \
  _claves_publicas _crear_par_de_llaves _desencriptar \
  _firmar_digitalmente _eliminar_clave _exportar_clave _subir_clave \
  _listar_archivos _importar_llave _revocar_clave _copiar_portapapeles _search_key

sec
