#!/bin/sh

header="[ctrl-b] activar driver
[tab] drivers desactivados
"
activar_driver() {
mod_path="/usr/lib/modules/$(uname -r)/kernel"
find $mod_path \
  -type f \
  -printf '%P\n'| fzf \
  --preview-window="down:wrap" \
  --preview "sudo modinfo $mod_path/{}" |
  xargs -r sudo modprobe
}

desactivar_driver() {
	sudo modprobe -r $1
}

{
  printf '%b\t\t%b\n' "\033[0;35mkernel version:" "$(uname -r)\033[0m"
	lsmod
} | fzf \
	--header-lines=2 \
	--header "$header" \
	--preview-window="down:wrap" \
  --ansi \
	--bind "ctrl-b:execute(desactivar_driver)" \
  --preview "sudo modinfo {1}"
#--preview "printf '\033[0;33m\n'; sudo modinfo {1}" \
