#!/bin/sh

activar_driver() {
  sudo modprobe $1
}

desactivar_driver() {
  sudo modprobe -r $1
}

{ printf '%s\t' "kernel version: "; uname -r; lsmod; } | fzf \
        --header-lines=2 \
         --preview-window="down:wrap:${PREVIEW_BORDER:-border-sharp}" \
        --preview "printf '\033[0;33m\n'; sudo modinfo {1}"
        #--preview "printf '\033[0;33m\n'; sudo modinfo {1}" \
