#!/bin/sh

# locale
#locale -a
{
  printf '%s\n' "marca para hacer toggle"
grep -i 'utf\|iso' /etc/locale.gen
} | fzf --header-lines 1 --layout=reverse --cycle -m |
  while read -r line; do
    if echo $line | grep '^#'; then
      sudo sed -i "/$line/s/^#//g" /etc/locale.gen
    else
      sudo sed -i "/$line/s/^/#/g" /etc/locale.gen
    fi
done | xargs -r sudo locale-gen
#locale -a | fzf --header "locales activos"
# sudo dpkg-reconfigure locales
